### PR TITLE
Add feedback and source section to about screen

### PR DESCRIPTION
**Pull request by Tunous**

### CODE REVIEW

**Comment by saket** [comment]
Maybe I should add you as a moderator to /r/GetDank. What's your reddit username?

**Comment by saket** [comment]
It's `Thanel` right?

**Comment by Tunous** [comment]
Yes, that's correct.

**Comment by saket** [comment]
Done!

**Comment by Tunous** [comment]
@saket Also, do you still have old screenshots and description from the play store saved somewhere?

**Comment by saket** [comment]
Yep. This folder has screenshots I used on Play Store as well as screenshots that show how the app shaped up over time: https://drive.google.com/open?id=1CswL6DQ8vNvqWc3fHuq7y6-PVSjZNlkJ

**Pull request merged**
