### PR TITLE
Allow cleartext traffic for proxy server

### PR DESCRIPTION
**Pull request by msfjarvis**
Fixes https://del.dog/uwikuqujeg.sql

### CODE REVIEW

**Comment by Tunous** [comment]
Hey, thank you for the fix!

Could you describe a simple use case how we could reproduce that issue to confirm the fix?

**Comment by msfjarvis** [comment]
> Hey, thank you for the fix!
> 
> Could you describe a simple use case how we could reproduce that issue to confirm the fix?

Trying to play a GIF will always re-download because the cache service will crash without this commit, you can confirm that by monitoring logcat for exceptions before and after the patch.

**Comment by Tunous** [comment]
I've reproduced the problem and confirmed that the fix indeed resolved the issue 👍

I'll squash this manually to also introduce changelog entry as single commit, hopefully it shouldn't remove your authorship of the commit.

**Comment by Tunous** [comment]
Squashed as d3bba456917c8984402ad49854968be3aeb5ddd5.

**Pull request closed without merging**
