### PR TITLE
Adds 'All' subreddit to the default list

### PR DESCRIPTION
**Pull request by Esselans**
You can't subscribe to /r/All so I added to the top of the list for all users (who are logged in or not)

2019-01-13 22_26_42-window

### CODE REVIEW

**Comment by Tunous** [comment]
I wonder whether it's a good idea to make that change. If I'm not mistaken All is same as Popular except that it also shows NSFW/controversial subreddits that Reddit would prefer not to show. How other Reddit apps deal with that? Perhaps it would be better to lock that feature behind a setting (or make it subscribe-able as local-only subscription) to only show All for these user who really want to see it.

**Comment by Esselans** [comment]
Hi! I don't like "All" subreddit either but is nice to have the option.

**Comment by saket** [comment]
What do you think about showing it only when `NSFW` filter is turned off in settings?

**Comment by Tunous** [comment]
I think I've found a simpler solution which also fixes a bug with subscribe button for /r/all. See #28

**Pull request closed without merging**
