### PR TITLE
Make it possible to locally subscribe to /r/all

### PR DESCRIPTION
**Pull request by Tunous**
A simple change which fixes the Subscribe button that shows up for /r/all. It makes it, so pressing on it will add /r/all to local database and show it just like /r/popular - with an option to remove from the edit screen.

### CODE REVIEW

**Comment by Tunous** [comment]
Oops missed the situation where local subscriptions are overridden when refreshing.... Will fix later.

**Comment by Tunous** [comment]
[APK for testing](https://127-162332333-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk). I'm ready to merge this, could anyone check it and tell whether it works correctly for them too?

**Comment by Esselans** [comment]
> [APK for testing](https://127-162332333-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk). I'm ready to merge this, could anyone check it and tell whether it works correctly for them too?

Just tested it, changes working fine here. Since it is locally saved it will be gone after logging out (which is perfectly normal). For the record, I did not try it with my switch account PR.

I know most people won't be switching accounts every now and then either have 2 or more accounts so I'm ok with this PR but not 100% conviced since on reddit web you have all, frontpage, popular and random like static subreddits.

**Comment by Tunous** [comment]
> I'm ok with this PR but not 100% conviced since on reddit web you have all, frontpage, popular and random like static subreddits.

We could also change it to behave like "Popular": Visible by default but can be removed manually.

**Comment by Esselans** [comment]
> > I'm ok with this PR but not 100% conviced since on reddit web you have all, frontpage, popular and random like static subreddits.
> 
> We could also change it to behave like "Popular": Visible by default but can be removed manually.

It's fine. Merge as it is now. Popular is the filtered version of /r/all so whoever wants to view it it's either 3 taps (clicks) or write down 3 letters. This PR is fine. Normal people have 1 account and subscribing to /r/all won't be a hassle.

**Pull request merged**
