### PR TITLE
Uprev Gradle to 5.6

### PR DESCRIPTION
**Pull request by msfjarvis**

### CODE REVIEW

**Comment by msfjarvis** [comment]
I had to re-fork the repository which broke the source repository for this PR, if you're unable to merge it please let me know and I'll open another one. Also, I can't seem to find the Bitrise log to see why it fails.

**Comment by Tunous** [comment]
> Also, I can't seem to find the Bitrise log to see why it fails.

That's an unfortunate limitation of Bitrise for publicly visible projects which requires builds for pull requests from forks to be approved before running. It's a bit annoying and I wasn't aware of that when adding Bitrise, but I really like how Bitrise works in general so I decided to keep it. We'll see how that will scale in future.

**Comment by msfjarvis** [comment]
> > Also, I can't seem to find the Bitrise log to see why it fails.
> 
> That's an unfortunate limitation of Bitrise for publicly visible projects which requires builds for pull requests from forks to be approved before running. It's a bit annoying and I wasn't aware of that when adding Bitrise, but I really like how Bitrise works in general so I decided to keep it. We'll see how that will scale in future.

I can see why they'd choose to do that, since build secrets can be exposed by malicious pull requests. I really like how Drone CI handles those, by allowing you to not export secrets in pull request builds thus avoiding the entire problem altogether, but that's a problem for another day.

**Comment by Tunous** [comment]
Yes, Bitrise also has that option and also allows to disable manual approval even if you have exposed some secrets. But it's not available for "public apps" where manual approval is always on.

**Comment by msfjarvis** [comment]
> Yes, Bitrise also has that option and also allows to disable manual approval even if you have exposed some secrets. But it's not available for "public apps" where manual approval is always on.

That seems pretty counterproductive on their part :(

**Comment by Esselans** [comment]
> But it's not available for "public apps" where manual approval is always on.

I think it's a nice feature to not build every single PR that gets modified in a public app that literally anyone could push anything and build it without any kind of approval

**Pull request merged**
