### PR TITLE
Highlight sticky submissions

### PR DESCRIPTION
**Pull request by Esselans**
Following the NSFW design I've added 2 more styles: Sticky and NSFW Sticky as shown below:

sticky_nsfw

Tell me what do you guys think?

### CODE REVIEW

**Comment by dotvhs** [comment]
First one looks really nice! Not sure if those colors are not too bright though? Anyway here's my attempt:
a01 copy 3

If you like them, here are hex values:
```
BG: #283028
Label: #9CF3AF
```

**Comment by dotvhs** [comment]
> @dotvhs can you suggest a color for both background and tag for the 'nsfw sticky'? since I'd like to update this branch with those 3 options:
> 
>     * Sticky (green)
> 
>     * NSFW (red/pink)
> 
>     * NSFW & Sticky (???)

I've been thinking about this and I'm not entirely sure. I came up with conclusion that perhaps different color is not needed, because NSFW + Sticky will be seen in 99% cases when whole subreddit is NSFW, so sticky could still be green, just with Sticky NSFW tag (where Sticky label would be green, NSFW pink but background still would be green). Probably for NSFW-only subreddits we don't even need that purple-ish background, only label.

**Comment by Esselans** [comment]
yeah I agree @dotvhs I'll do some changes and post some more images

**Comment by Esselans** [comment]
Final screenshot:

screenshot_1547861998

**Pull request merged**
