### PR TITLE
[WIP] Support for multiple accounts

### PR DESCRIPTION
**Pull request by Esselans**
## Description

Allow Dank to store multiple sessions and switch between them without login in again.

## Preview

(Sorry for the gif quality. I will edit with a new gif later)

> The gif has some latency and it looks far worse than on the device.
 

## WIP List 
- [x] Fix some **serious** UI issues 
- [x] Message polling seems to be working for all users and not just the active one
- [ ] Code clean up
- [ ] Testing
- [ ] Find a better spot to put the switch-user list ?
- [ ] Remove Karma count on an userless user
- [x] Update the toolbar title back to the correct username
- [ ] Remove account from the list onLogout()

### CODE REVIEW

**Comment by Esselans** [comment]
This need a lot of work but it's a start.

**Comment by Esselans** [comment]
If someone could test this also I'll appreciate that. I'm having some crash while switching between user and userless mode that I couldn't identify yet.

**Comment by Tunous** [comment]
Automatically built apk for interested: https://47-162332333-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk

@Esselans unless that was your intention you might want to check git config on your pc (username, email) because GitHub shows blank avatar for your commits.

**Comment by Esselans** [comment]
> Automatically built apk for interested: https://47-162332333-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk

Thanks for this!

> @Esselans unless that was your intention you might want to check git config on your pc (username, email) because GitHub shows blank avatar for your commits.

Fixed! Thanks for the heads up.

**Comment by dotvhs** [comment]
Perhaps something like this?

### Single account menu (add account on the right)
a01 copy 5
### Multi account menu (new option shows up)
a01 copy 6
a01 copy 7

**Comment by Esselans** [comment]
I like that. It's a good option. Let me try to do it on the app. I'm not good at this lol.

+1

**Comment by Tunous** [comment]
@Esselans hey, what's the reason for closing this? Are you working on another implementation perhaps? Just asking because it's still a nice feature to have.

**Comment by Esselans** [comment]
@Tunous Hi!.. Actually I am, yes. But with all the other changes I'm working on a new branch with a different approach.

**Comment by dotvhs** [comment]
Are any designs needed? :)

**Comment by Esselans** [comment]
@dotvhs check #37

**Pull request closed without merging**
