### PR TITLE
[WIP] Multi Account

### PR DESCRIPTION
**Pull request by Esselans**
Using the same approach with App Shortcuts I'm working on the multi account support since the reddit library already supports it. 

It allows to add/remove accounts (using a Repository), switch to another or logout (while keeping the authentication data). The list can also be ordered by drag 'n' drop (same as app shortcuts). 

 
b_accounts

- [x] Able to Login (add account)

- [x] Store users 

- [x] Switch between users

- [x] Delete an account  (Although no confirmation)

- [x] Add delete confirmation ?

- [x] Logout and become userless

- [x] Improve swipe actions

- [ ] See DB Migration Issue

- [ ] Investigate crashes 

- [ ] Testing

- [ ] Code Clean Up
 
- [ ] ~~Use Kotlin classes~~

### CODE REVIEW

**Comment by Tunous** [comment]
Quick problem: On fresh install when you have no accounts added application crashes when you click on profile icon.

**Comment by Tunous** [comment]
Also, is there any reason why you decided to implement new classes in Java instead of Kotlin? I would generally prefer to have the codebase move more into Kotlin side so it would be good to have all new code written in Kotlin. Unless there is a strong reason why we wouldn't want to do that.

**Comment by Esselans** [comment]
Well that crash is new to me. I stil have a lot to do with this, so I'll check that when I can. 

I end up using the java classes since I the UI is based on the App Shortcuts. I'll make checkbox for that.

**Comment by Tunous** [comment]
> I end up using the java classes since I the UI is based on the App Shortcuts. I'll make checkbox for that.

Ok, I see. I would suggest to go for Kotlin in any new classes in future. Here you can leave this in Java since you already wrote working code. But if you want to change it's up to you to decide :)

**Comment by Esselans** [comment]
> Ok, I see. I would suggest to go for Kotlin in any new classes in future. Here you can leave this in Java since you already wrote working code. But if you want to change it's up to you to decide :)

Nice. I didn't know that. Will do for sure.

**Comment by Esselans** [comment]
> Quick problem: On fresh install when you have no accounts added application crashes when you click on profile icon.
> 
> ```
> Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
> 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> 	at java.lang.Thread.getStackTrace(Thread.java:1538)
> 	at io.reactivex.Flowable.scanWith(Flowable.java:12176)
> 	at io.reactivex.Flowable.scan(Flowable.java:12136)
> 	at me.saket.dank.utils.RxDiffUtil.lambda$calculateDiff$3(RxDiffUtil.java:46)
> 	at me.saket.dank.utils.-$$Lambda$RxDiffUtil$6HorHZveN0l7jbBNwJhmbIeQPVc.apply(Unknown Source:4)
> 	at io.reactivex.Flowable.compose(Flowable.java:6658)
> 	at me.saket.dank.ui.usermanagement.UserManagementActivity.setupUserList(UserManagementActivity.java:247)
> 	... 14 more
> Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
> 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> 	at java.lang.Thread.getStackTrace(Thread.java:1538)
> 	at io.reactivex.Flowable.skip(Flowable.java:12340)
> 	at me.saket.dank.utils.RxDiffUtil.lambda$calculateDiff$3(RxDiffUtil.java:51)
> 	... 17 more
> Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
> 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> 	at java.lang.Thread.getStackTrace(Thread.java:1538)
> 	at io.reactivex.Flowable.fromPublisher(Flowable.java:2127)
> 	... 16 more
> Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
> 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> 	at java.lang.Thread.getStackTrace(Thread.java:1538)
> 	at io.reactivex.Flowable.observeOn(Flowable.java:9943)
> 	at io.reactivex.Flowable.observeOn(Flowable.java:9866)
> 	at me.saket.dank.ui.usermanagement.UserManagementActivity.setupUserList(UserManagementActivity.java:248)
> 	... 14 more
> Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
> 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> 	at java.lang.Thread.getStackTrace(Thread.java:1538)
> 	at io.reactivex.Flowable.takeUntil(Flowable.java:13862)
> 	at me.saket.dank.ui.usermanagement.UserManagementActivity.setupUserList(UserManagementActivity.java:249)
> 	... 14 more
> ```

After uninstalling/installing the app db migration won't execute and I can't use onCreate() since it is only called once when db does not exists.

**Comment by Esselans** [comment]
Closing because going stale. I'll create PR when it's done.

**Pull request closed without merging**
